version: 2
defaults: &defaults
  docker:
    - image: cimg/python:3.11.0-browsers
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            sudo apt update
            sudo apt install jq
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker==6.1.3

install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-la-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-la-{{ checksum "package-lock.json" }}
  paths:
    - node_modules

builddeploy_steps: &builddeploy_steps
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: ./builddocker.sh ${APPNAME}
      - save_cache: *save_cache_settings
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh $DEPLOY_ENV
            source awsenvconf
            ./buildenv.sh -e $DEPLOY_ENV -b ${DEPLOY_ENV}-${APPNAME}-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e $DEPLOY_ENV -t latest -s ${DEPLOY_ENV}-global-appvar,${DEPLOY_ENV}-${APPNAME}-appvar -i ${APPNAME}
jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    environment:
      DEPLOY_ENV: "dev"
      APPNAME: "topcoder-x-receiver"
    steps: *builddeploy_steps

  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    environment:
      DEPLOY_ENV: "prod"
      APPNAME: "topcoder-x-receiver"
    steps: *builddeploy_steps

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - develop
      - "build-prod":
          context : org-global
          filters:
            branches:
              only:
                - master
